import mysql.connector
con=mysql.connector.connect(user="root", password="tiger", database="school")
cur=con.cursor()
print("----------------------MY SQL CONNECTIVITY-1----------------------")
print()
admnno=int(input("\t     Enter the admission no.  : "))
name=input("\t     Enter the name           : ")
clas=input("\t     Enter the class          : ")
contactNo=input("\t     Enter the contact no.    : ")
marks=int(input("\t     Enter the marks          : "))
query= "INSERT INTO student VALUES({}, '{}', '{}', '{}', {})".format(admnno, name, clas, contactNo, marks)
cur.execute(query)
cur.execute("COMMIT")
print("*"*65)
print("*                   RECORD SUCCESSFULLY ADDED                   *")
print("*"*65)
print()
print("-"*65)
